---
title: "Linear Regression - Conceptual"
output: html_notebook
---
**1. Describe the null hypotheses to which the p-values given in Table 3.4
correspond. Explain what conclusions you can draw based on these
p-values. Your explanation should be phrased in terms of sales, TV,
radio, and newspaper, rather than in terms of the coefficients of the
linear model.**

* For the intercept parameter, the null hypothesis that mean sales equals zero when all other predictors equal zero. For the other parameters the null hypothesis is that these is no relationship between sales and each of the predictors TV, radio and newspaper individually. 
* The small p value for the intercept term means we can reject the null hypothesis that mean sales equals zero when all other predictors equals zero
* The small p value for TV and radio means we can reject the null hypothesis that there is no relationship between sales and TV / radio
* The large p value for newspaper means we cannot reject the null hypothesis that there is no relationship between sales and newspaper

**2. Carefully explain the differences between the KNN classifier and KNN
regression methods.**



3. Suppose we have a data set with five predictors, X1 = GPA, X2 = IQ,
X3 = Gender (1 for Female and 0 for Male), X4 = Interaction between
GPA and IQ, and X5 = Interaction between GPA and Gender. The
response is starting salary after graduation (in thousands of dollars).
Suppose we use least squares to fit the model, and get βˆ0 = 50, βˆ1 =
20, βˆ2 = 0.07, βˆ3 = 35, βˆ4 = 0.01, βˆ5 = −10.
(a) Which answer is correct, and why?
i. For a fixed value of IQ and GPA, males earn more on average
than females.
ii. For a fixed value of IQ and GPA, females earn more on
average than males.
iii. For a fixed value of IQ and GPA, males earn more on average
than females provided that the GPA is high enough.
iv. For a fixed value of IQ and GPA, females earn more on
average than males provided that the GPA is high enough.
(b) Predict the salary of a female with IQ of 110 and a GPA of 4.0.
(c) True or false: Since the coefficient for the GPA/IQ interaction
term is very small, there is very little evidence of an interaction
effect. Justify your answer.
4. I collect a set of data (n = 100 observations) containing a single
predictor and a quantitative response. I then fit a linear regression
model to the data, as well as a separate cubic regression, i.e. Y =
β0 + β1X + β2X2 + β3X3 + .
(a) Suppose that the true relationship between X and Y is linear,
i.e. Y = β0 + β1X + . Consider the training residual sum of
squares (RSS) for the linear regression, and also the training
RSS for the cubic regression. Would we expect one to be lower
than the other, would we expect them to be the same, or is there
not enough information to tell? Justify your answer.

Answer (a) using test rather than training RSS.
(c) Suppose that the true relationship between X and Y is not linear,
but we don’t know how far it is from linear. Consider the training
RSS for the linear regression, and also the training RSS for the
cubic regression. Would we expect one to be lower than the
other, would we expect them to be the same, or is there not
enough information to tell? Justify your answer.
(d) Answer (c) using test rather than training RSS.
5. Consider the fitted values that result from performing linear regression without an intercept. In this setting, the ith fitted value takes
the form
yˆi = xiβ, ˆ
where
βˆ =
n
i=1
xiyi

/
n
i=1
x2
i

. (3.38)
Show that we can write
yˆi = n
i=1
aiyi .
What is ai?
Note: We interpret this result by saying that the fitted values from
linear regression are linear combinations of the response values.
6. Using (3.4), argue that in the case of simple linear regression, the
least squares line always passes through the point (¯x, y¯).
7. It is claimed in the text that in the case of simple linear regression
of Y onto X, the R2 statistic (3.17) is equal to the square of the
correlation between X and Y (3.18). Prove that this is the case. For
simplicity, you may assume that ¯x = ¯y = 0.